### ISSUE TITLE
Error installing from ethpm

### ISSUE THREAD

**Issue by dmichael** [ConsenSys/Tokens#44]
When installing these tokens from the ethpm registry, there is an error. However, a few of the contracts do get installed. `HumanStandardToken.sol`, `StandardToken.sol`, and `Token.sol` are installed even with the error. These contracts do not match the `ethpm.json` manifest.

```bash
$ truffle install tokens
Error: Could not find object at hash 'QmSMdCxaH1H5TfyjKVtiPKnFabkQByciTBG6FTCAiCufX7' in 5000ms
    at Timeout._onTimeout (/Users/<username>/.nvm/versions/node/v6.10.0/lib/node_modules/truffle/node_modules/ethpm/lib/hosts/ipfshost.js:47:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by simondlr** [comment]
Hey @skmgoldin. Any thoughts there? ^^

**Comment by skmgoldin** [comment]
The tokens repo disappeared for a long time to due to IPFS and Ropsten problems. It's back now: https://github.com/trufflesuite/truffle/issues/378
